### ISSUE TITLE
Unable to save context

### ISSUE THREAD

**Issue by rasvaan** [jrvosse/image_annotation#7]
I am trying to save how someone reached a certain object that he is annotating. In the prolog backend I added code for getting the parameter and in the javascript I added code to create a string describing this context:
![screen shot 2015-03-14 at 13 15 34](https://cloud.githubusercontent.com/assets/1213099/6651808/9448706e-ca4d-11e4-86d5-ed3afea2d724.png)
When I try to send this to the backend by adding the property:
![screen shot 2015-03-14 at 13 22 20](https://cloud.githubusercontent.com/assets/1213099/6651811/a48928c4-ca4d-11e4-9922-dba96bedeb00.png)
I get the following error:
![screen shot 2015-03-14 at 13 22 59](https://cloud.githubusercontent.com/assets/1213099/6651812/b1ab91c2-ca4d-11e4-9082-bfbfb496e33c.png)
I suspect something in the annotatorius.min.js has to be added?

**Comment by jrvosse** [comment]
Hi Chris,

Unless this is some trivial typo (the error message you show makes it really look like there is some weird spurious character (non utf8?) _after_ the last comma in:
reached_object_with: context,<XXX illegal property starting here>)...

Nut in general: You need to give me the information I need to reproduce this.  The code you show above does not even appear in my git ... ?!  Can't you just check this in and push it (e.g. on an issue7 branch)?

**Comment by rasvaan** [comment]
Ha Jacco,
Thanks for the reply, it was indeed a non utf8 char not showing up in xcode. After removing it the code worked (so far for my google for error messages powers, think they vanished because of pre-demo stress).

Next time I will be more thorough in describing the problem and how to recreate it. It was in a separate branch but I did not mention this.
