### ISSUE TITLE
Startpoint bounding box alway top left

### ISSUE THREAD

**Issue by rasvaan** [jrvosse/image_annotation#8]
In Firefox (using v31.7.0) drawing the annotorious bounding box always starts in the top left corner of the image. You can run this for example at http://annotate.accurator.nl, login: kip ww: aap. After loggin in go to the following url:
http://annotate.accurator.nl/annotate_image.html?uri=http://purl.org/collections/nl/rma/BK-1958-44

![screen shot 2015-06-15 at 15 44 52](https://cloud.githubusercontent.com/assets/1213099/8161181/7ed7dcb2-1375-11e5-8287-cb80bae544c5.png)

This works correctly in safari/chrome and loading the plain annotorious annotation component does not have the same problem:

![screen shot 2015-06-15 at 15 48 05](https://cloud.githubusercontent.com/assets/1213099/8161251/ef2d7a9e-1375-11e5-894b-6f9342a435db.png)
Found it hard to narrow down the problematic code, please let me know if I can/should provide more info.

**Comment by jrvosse** [comment]
Chris, 

This was caused by a sloppy implicit variable in a for loop.  Not sure why this bug was only triggered in Firefox. It has been fixed by cb353a8f5f47343b703f13c81eb0421194713aec.

Jacco

**Comment by rasvaan** [comment]
This does not seem to solve the problem. I updated the code in the cpack and upgraded the server, still having the same problem using FireFox 31.7.0:
http://annotate.accurator.nl/annotate_image.html?uri=http://purl.org/collections/nl/rma/AK-KOG-313-15
![screen shot 2015-06-17 at 10 28 02](https://cloud.githubusercontent.com/assets/1213099/8202588/9fde808e-14db-11e5-9090-77d5a5a86570.png)

**Comment by jrvosse** [comment]
Hi Chris,

I am not sure what is going on.  I can confirm I get the same bug with my FF on your server either.
I cannot reproduce this, however, on my own local servers, not on linux nor on mac. On my local deployment I did get the bug before the fix, but not after... :-(  Maybe it is something in the interaction with accurator?

**Comment by rasvaan** [comment]
I'll start adding the var in the loops and let you know if that helps!

**Comment by rasvaan** [comment]
Done, this does fix it.
